Controllers/AccommodationController.cs
using EgyptTouristWebSite.Context;
using EgyptTouristWebSite.Models;
using EgyptTouristWebSite.Repository;
using EgyptTouristWebSite.Repository.Interfaces;
using EgyptTouristWebSite.Services;
using EgyptTouristWebSite.Services.Interfaces;
using EgyptTouristWebSite.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Numerics;

namespace EgyptTouristWebSite.Controllers
{
    public class AccommodationController : Controller
    {
      
        private readonly IAccommodationService accService;
        private readonly IAccommodationRepo accRepo;
        private readonly IUserService userService;

        public AccommodationController(IAccommodationService _accService,IAccommodationRepo _accRepo,IUserService userService)
        {
            accService = _accService;
            accRepo = _accRepo;
            this.userService = userService;
        }

        public IActionResult ShowAllPlaces()
        {
            AccommodationsViewModel accModel = accService.GetAccommodationVM();
            Console.WriteLine(accModel.accMotels.Count);
            Console.WriteLine(accModel.accHotels.Count);
            Console.WriteLine(accModel.accResorts.Count);
            Console.WriteLine(accModel.accsList.Count);

            return View(accModel);
        }
        public IActionResult ShowFilteredPlaces(string[] types, string[] prices, string[] ratings)
        {
            var places = accService.Filter(types, prices, ratings);
            return PartialView("FilteredAccommodationsPartial", places);
        }
        [Authorize]
        public IActionResult Details(int id)
        {
            var acc = accRepo.GetById(id);
            if (acc == null) return NotFound();

            return View(acc);
        }
        public IActionResult SearchByName(string searchString)
        {
            if (string.IsNullOrWhiteSpace(searchString)) { return Ok(); }
            var places = accRepo.GetByName(searchString);
            return PartialView("FilteredAccommodationsPartial", places);
        }
        public IActionResult ShowPlacesByCategory(string category)
        {
            dynamic places = accRepo.GetByCat(category);
            return View(places);
        }
        [Authorize]
        public IActionResult Delete(int id)
        {
            accRepo.Delete(id);
            return View();
        }
        [Authorize]
        //[ValidateAntiForgeryToken]

        public async Task<IActionResult> Reserve(Accommodation acc)
        {
            Accommodation accToReserve = accRepo.GetById(acc.Id);
          bool res= await userService.AddAccommodation(accToReserve, User.Identity.Name);
            if (res)
            {
                return RedirectToAction("Profile", "Account", new {name=User.Identity.Name});
            }
            else
            {
                return BadRequest();
            }

        }
    }
}

Controllers/InterestingPlaceController.cs
using EgyptTouristWebSite.Context;
using EgyptTouristWebSite.Models;
using EgyptTouristWebSite.Repository;
using EgyptTouristWebSite.Repository.Interfaces;
using EgyptTouristWebSite.Services;
using EgyptTouristWebSite.Services.Interfaces;
using EgyptTouristWebSite.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EgyptTouristWebSite.Controllers
{
    public class InterestingPlaceController : Controller
    {
        private readonly IInterPlaceService placeService;
        private readonly IPlaceRepo placeRepo;
        private readonly IprofileService profileService;

        public InterestingPlaceController(IInterPlaceService _placeService,IPlaceRepo _placeRepo,IprofileService profileService)
        {
            placeService = _placeService;
            placeRepo = _placeRepo;
            this.profileService = profileService;
        }



        public IActionResult ShowAllPlaces()
        {
            PlacesViewModel model = placeService.GetPlaceVM();
            return View(model);
        }
        [ValidateAntiForgeryToken]
        public IActionResult ShowPlacesByCategory(string category)
        {
            dynamic places = placeRepo.GetByCat(category);
            return View(places);
        }
        //[ValidateAntiForgeryToken]
        [Authorize]
       // [Route("{id}")]
        public IActionResult Details(int id)
        {
            var place = placeRepo.GetById(id);
            return View(place);
        }
        public IActionResult SearchByName(string name)
        {
            var place = placeRepo.GetByName(name);
            return View(place);
        }
        [ValidateAntiForgeryToken]
        [Authorize]
        public IActionResult Delete(int id)
        {
            placeRepo.Delete(id);
            return View();  // Redirect To Action of Admin List of places
        }
        [Authorize]
        public async Task<IActionResult> Reserve(InterestingPlace place)
        {
            InterestingPlace placeToReserve = placeRepo.GetById(place.Id);
            bool res = await profileService.AddPlace(placeToReserve, User.Identity.Name);
            if (res)
            {
                return RedirectToAction("Profile", "Account", new { name = User.Identity.Name });
            }
            else
            {
                return BadRequest();
            }

        }



    }
}

Controllers/ServiceController.cs
using EgyptTouristWebSite.Context;
using EgyptTouristWebSite.Models;
using EgyptTouristWebSite.Repository;
using EgyptTouristWebSite.Repository.Interfaces;
using EgyptTouristWebSite.Services;
using EgyptTouristWebSite.Services.Interfaces;
using EgyptTouristWebSite.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EgyptTouristWebSite.Controllers
{
    public class ServiceController : Controller
    {

        private readonly IServicesService _servicesService;
        private readonly IServiceRepo _serviceRepo;
        private readonly IprofileService _profileService;
        public ServiceController(IServiceRepo serviceRepo,IServicesService servicesService, IprofileService profileService)
        {
            _serviceRepo = serviceRepo;
            _servicesService = servicesService;
            _profileService = profileService;

        }

        public IActionResult ShowAllServices()
        {
            var allServices = _servicesService.GetServiceVM();
            return View(allServices);
        }
        public IActionResult ShowServicesByCategory(string category)
        {
            var serviceCat = _serviceRepo.GetByCat(category);
            return View(serviceCat);
        }
        //[ValidateAntiForgeryToken]
        [Authorize]
        public IActionResult Details(int id)
        {
            var service = _serviceRepo.GetById(id);
            return View(service);
        }
        [ValidateAntiForgeryToken]
        [Authorize]
        public IActionResult Delete(int id)
        {
            _serviceRepo.Delete(id);
            return View();
        }

        [Authorize]
        public async Task<IActionResult> Reserve(Service service)
        {
            Service serviceToAdd = _serviceRepo.GetById(service.Id);
            bool res = await _profileService.AddServices(serviceToAdd, User.Identity.Name);
            if (res)
            {
                return RedirectToAction("Profile", "Account", new { name = User.Identity.Name });
            }
            else
            {
                return BadRequest();
            }

        }
    }
}

Controllers/TravelAgencyController.cs
using EgyptTouristWebSite.Context;
using EgyptTouristWebSite.Models;
using EgyptTouristWebSite.Repository;
using EgyptTouristWebSite.Repository.Interfaces;
using EgyptTouristWebSite.Services;
using EgyptTouristWebSite.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EgyptTouristWebSite.Controllers
{
    public class TravelAgencyController : Controller
    {
        private readonly ITravelAgencyRepo _travelAgencyRepo;
        private readonly IprofileService _profileService;
        public TravelAgencyController(ITravelAgencyRepo travelAgencyRepo, IprofileService profileService)
        {
            _travelAgencyRepo = travelAgencyRepo;
            _profileService = profileService;
        }

        public IActionResult ShowAllPlaces()
        {
            var Allagency = _travelAgencyRepo.GetAll();
            return View(Allagency);
        }
       // [ValidateAntiForgeryToken]
        [Authorize]
        public IActionResult Details(int id)
        {
            var agency = _travelAgencyRepo.GetById(id);
            return View(agency);
        }
        [ValidateAntiForgeryToken]
        [Authorize]
        public IActionResult Delete(int id)
        {
            _travelAgencyRepo.Delete(id);
            return View();
        }
        [Authorize]
        public async Task<IActionResult> Reserve(TravelAgency travelAgency)
        {
            TravelAgency travelToAdd = _travelAgencyRepo.GetById(travelAgency.Id);
            bool res = await _profileService.AddTravelAgency(travelToAdd, User.Identity.Name);
            if (res)
            {
                return RedirectToAction("Profile", "Account", new { name = User.Identity.Name });
            }
            else
            {
                return BadRequest();
            }

        }
    }
}

Views/Shared/MapPartialView.cshtml
@using Newtonsoft.Json;
@{
    ViewData["Title"] = "Home Page";

}

<script src="~/lib/jquery/dist/jquery.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/ol@v7.3.0/dist/ol.js"></script>
<link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/ol@v7.3.0/ol.css" />
<div class="section-gis">
   
        <nav class="navbar navbar-default" id="search">
            <input type="text"
                    name="search"
                    class="form-control"
                    id="searchbox"
                    placeholder="Where to" />
                <ul class="list-group" id="placeopetion"></ul>
                <select placeholder="Basemaps" id="basemapselector" class="dropdown-menu" name="selectbox">
            <option value="OSM" >OSM</option>
            <option value="Esri" selected>Imagery</option>
                </select>

                <div class="form-group" id="layers" >
                    <ul id="checkbox-list" class="form-check form-check-inline">
                    </ul>
                </div>
        </nav>
       <div id="map"></div>
      
</div>

<div class="pop" >
    
     <img id="image" >
        <div class="body">
            <h6 id="name"></h6>
        
        <a id="go" class="btn btn-primary">Details</a>
        </div>
</div>
<style>
    .section-gis{
        justify-content: center;
        border: 1px solid rgb(210, 215, 211);
        border-top-left-radius: 10px;
        border-top-right-radius: 10px;
        width: 100%;
        /* margin-left: 50px; */
        display: flex;
        flex-wrap: nowrap;
        flex-flow: column;
        /* align-self: center; */
        align-items: center;
        margin: 0px;
    }
 
    #map {
        width: 70%;
        height: 500px;
        
    }
    #search {
  
        position: relative;
        background-color: rgba(0, 0, 0, 0.01);
        width:70%;
        justify-content: flex-start;
       
    }

    #searchbox {
        margin-top:5px;
        margin-bottom: 5px;
        margin-left:50px;
         width:400px;
        transition: 0.3s;
    }

    #placeopetion {
        display: flex;
        width: 400px;
        overflow: auto;
        display: inline;
        position: absolute;
        top: 65px;
        left: 50px;
        z-index: 2;
        list-style-type: none;
        transition: 0.3s;
    }
    #placeopetion li{
            background-color: rgba(255, 255, 255, 0.25);
    }

    #placeopetion input{
        padding:5px;
    }
    #basemapselector{
      
        display:block;
        position:unset;
        margin-left:50px;
    }
    #layers{
        list-style-type: none;
        margin-left:40px;
    }
    #layers li{
            float: left;
            padding:10px;
        }
    .checkbox-list {

        list-style: none;
        margin: 0;
        padding: 0;
        display:inline-block;
        
    }

 /*  map_popup_style*/

    .pop {
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        transition: 0.3s;
        border-radius: 5px;
        width: 130px;
        height: 180px;
        display: inline-block;
        background-color: rgb(210, 215, 225);
        font-size:small;
    }

   

    #image {
        border-radius: 5px 5px 0 0;
        width: 100%;
        height: 100px;
        object-fit: cover;
    }
    #go{
      padding:2px;

    }
</style>


<script src="~/js/site.js" asp-append-version="true"></script>
    <script>


        let map = CreateMap();
        //change basemap handeler
     
         changebasemap(map);
         //geocoding
         Geocoding(map);
         //jason from model                

</script>






  

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EgyptTouristWebSite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <link rel="stylesheet" href="~/EgyptTouristWebSite.styles.css" asp-append-version="true" />


</head>
<body>
    <header>

            <nav class="sticky">
                <div class="nav-content">
                  <div class="logo">
                    <a href="#">Traveler's Haven.</a>
                  </div>
                  <ul class="nav-links">
                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="InterestingPlace" asp-action="ShowAllPlaces">Places</a></li>
                    <li><a asp-area="" asp-controller="Accommodation" asp-action="ShowAllPlaces">Accomedation</a></li>
                    <li><a asp-area="" asp-controller="Service" asp-action="ShowAllServices">Service</a></li>
                    <li><a asp-controller="TravelAgency" asp-action="ShowAllPlaces">Travel Agency</a></li>
                    @if (User.Identity.IsAuthenticated){
                        <a href="/account/profile/@User.Identity.Name" class="user-name">@User.Identity.Name</a>
                        <li><a asp-controller="Account" asp-action="Signout"> Sign Out</a></li>
                        if (User.IsInRole("Admin")){

                            <li><a asp-controller="Dashboard" asp-action="Index"> DashBoard</a></li>
                        }
                    }else{
                    <li><a asp-controller="Account" asp-action="Register"> Registration</a></li>
                    <li><a asp-controller="Account" asp-action="Login"> Sign In</a></li>
                    }
                </ul>
                </div>
              </nav>


    </header>
    <div class="container" style="padding-top: 100px">
        <main role="main" class="pb-3">
            @RenderBody()      
        </main>
    </div>

    <footer>
    <div class="content">
      <div class="top">
        <div class="logo-details">
          <i class="fab fa-slack"></i>
          <span class="logo_name">ITI</span>
        </div>
        <div class="media-icons">
          <a href="#"><i class="fab fa-facebook-f"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-linkedin-in"></i></a>
          <a href="#"><i class="fab fa-youtube"></i></a>
        </div>
      </div>
      <div class="link-boxes">
        <ul class="box">
          <li class="link_name">Company</li>
          <li><a href="#">Home</a></li>
          <li><a href="#">Contact us</a></li>
          <li><a href="#">About us</a></li>
          <li><a href="#">Get started</a></li>
        </ul>
        <ul class="box">
          <li class="link_name">Services</li>
          <li><a asp-area="" asp-controller="InterestingPlace" asp-action="ShowAllPlaces">Places</a></li>
          <li><a asp-area="" asp-controller="Accomedation" asp-action="ShowAllServices">Accomedation</a></li>
          <li><a asp-controller="Service" asp-action="ShowAllPlaces">Service</a></li>
          <li><a asp-controller="TravelAgency" asp-action="ShowAllPlaces">Travel Agency</a></li>
        </ul>
        <ul class="box">
          <li class="link_name">Account</li>
          <li><a href="/Account/Profile/@User.Identity.Name">Profile</a></li>
          <li><a href="#">My account</a></li>
          <li><a href="#">Prefrences</a></li>
          <li><a href="#">Purchase</a></li>
        </ul>
@*
        <ul class="box">
          <li class="link_name">Courses</li>
          <li><a href="#">HTML & CSS</a></li>
          <li><a href="#">JavaScript</a></li>
          <li><a href="#">Photography</a></li>
          <li><a href="#">Photoshop</a></li>
        </ul>*@

        <ul class="box input-box">
          <li class="link_name">Subscribe</li>
          <li><input type="text" placeholder="Enter your email"></li>
          <li><input type="button" value="Subscribe"></li>
        </ul>

      </div>
    </div>
    <div class="bottom-details">
      <div class="bottom_text">
        <span class="copyright_text">Copyright &#169; 2021 <a href="#">CodingLab.</a>All rights reserved</span>
        <span class="policy_terms">
          <a href="#">Privacy policy</a>
          <a href="#">Terms & condition</a>
        </span>
      </div>
    </div>
  </footer>
   @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - EgyptTouristWebSite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'>
        </script> @*Font Awesome for Icons*@



    @await RenderSectionAsync("Scripts", required: false)


</body>
</html>
<style>

 nav{
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  padding: 20px;
  transition: all 0.4s ease;
}
nav.sticky{
  display: block;
  padding: 15px 20px;
  background: #140B5C;
  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.1);
    z-index: 1002; /* Add this line to make the navbar stay on top */

}

nav .nav-content{
  height: 100%;
  max-width: 1200px;
  margin: auto;
  display: flex;
  align-items: center;
  justify-content: space-between;
}
nav .logo a{
  font-weight: 500;
  font-size: 35px;
  color: #4070f4;
}
nav.sticky .logo a{
  color: #fff;
  text-decoration: none;
}
.logo a:hover{
  transform: scale(1.1);
}
.nav-content .nav-links{
  display: flex;
}
.nav-content .nav-links li{
  list-style: none;
  margin: 0 8px;
}
 .nav-links li a{
  text-decoration: none;
  color: #0E2431;
  font-size: 18px;
  font-weight: 500;
  padding: 10px 4px;
  transition: all 0.3s ease;
}
 .nav-links li a:hover{
     color: #fff;
  background-color: #4070f4;

  border-radius:20px
 }
 nav.sticky .nav-links li a{
   color: #fff;
   transition: all 0.4s ease;
}
 nav.sticky .nav-links li a:hover{
  color: #0E2431;
}

    .user-name {
        color: aqua;
        font-size: larger;
        cursor: pointer;
        text-decoration: none;
    }



    /* Google Font CDN Link */

body{
  min-height: 100vh;
  width: 100%;
  background: #EEECEB;
}
footer{
  background: #140B5C;
  width: 100%;
  bottom: 0;
  left: 0;
  z-index: 1;
}
footer::before{
  content: '';
  position: absolute;
  left: 0;
  top: 100px;
  height: 1px;
  width: 100%;
  background: #AFAFB6;
}
footer .content{
  max-width: 1250px;
  margin-bottom: 0px; /* add a margin to ensure content isn't hidden */
  padding: 30px 40px 40px 40px;
}
.content {
  margin-bottom: 100px; /* add a margin to ensure content isn't hidden */
}

footer .content .top{
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 50px;
}
.content .top .logo-details{
  color: #fff;
  font-size: 30px;
}
.content .top .media-icons{
  display: flex;
}
.content .top .media-icons a{
  height: 40px;
  width: 40px;
  margin: 0 8px;
  border-radius: 50%;
  text-align: center;
  line-height: 40px;
  color: #fff;
  font-size: 17px;
  text-decoration: none;
  transition: all 0.4s ease;
}
.top .media-icons a:nth-child(1){
  background: #4267B2;
}
.top .media-icons a:nth-child(1):hover{
  color: #4267B2;
  background: #fff;
}
.top .media-icons a:nth-child(2){
  background: #1DA1F2;
}
.top .media-icons a:nth-child(2):hover{
  color: #1DA1F2;
  background: #fff;
}
.top .media-icons a:nth-child(3){
  background: #E1306C;
}
.top .media-icons a:nth-child(3):hover{
  color: #E1306C;
  background: #fff;
}
.top .media-icons a:nth-child(4){
  background: #0077B5;
}
.top .media-icons a:nth-child(4):hover{
  color: #0077B5;
  background: #fff;
}
.top .media-icons a:nth-child(5){
  background: #FF0000;
}
.top .media-icons a:nth-child(5):hover{
  color: #FF0000;
  background: #fff;
}
footer .content .link-boxes{
  width: 100%;
  display: flex;
  justify-content: space-between;
}
footer .content .link-boxes .box{
  width: calc(100% / 5 - 10px);
}
.content .link-boxes .box .link_name{
  color: #fff;
  font-size: 18px;
  font-weight: 400;
  margin-bottom: 10px;
  position: relative;
}
.link-boxes .box .link_name::before{
  content: '';
  position: absolute;
  left: 0;
  bottom: -2px;
  height: 2px;
  width: 35px;
  background: #fff;
}
.content .link-boxes .box li{
  margin: 6px 0;
  list-style: none;
}
.content .link-boxes .box li a{
  color: #fff;
  font-size: 14px;
  font-weight: 400;
  text-decoration: none;
  opacity: 0.8;
  transition: all 0.4s ease
}
.content .link-boxes .box li a:hover{
  opacity: 1;
  text-decoration: underline;
}
.content .link-boxes .input-box{
  margin-right: 55px;
}
.link-boxes .input-box input{
  height: 40px;
  width: calc(100% + 55px);
  outline: none;
  border: 2px solid #AFAFB6;
  background: #140B5C;
  border-radius: 4px;
  padding: 0 15px;
  font-size: 15px;
  color: #fff;
  margin-top: 5px;
}
.link-boxes .input-box input::placeholder{
  color: #AFAFB6;
  font-size: 16px;
}
.link-boxes .input-box input[type="button"]{
  background: #fff;
  color: #140B5C;
  border: none;
  font-size: 18px;
  font-weight: 500;
  margin: 4px 0;
  opacity: 0.8;
  cursor: pointer;
  transition: all 0.4s ease;
}
.input-box input[type="button"]:hover{
  opacity: 1;
}
footer .bottom-details{
  width: 100%;
  background: #0F0844;
}
footer .bottom-details .bottom_text{
  max-width: 1250px;
  margin: auto;
  padding: 20px 40px;
  display: flex;
  justify-content: space-between;
}
.bottom-details .bottom_text span,
.bottom-details .bottom_text a{
  font-size: 14px;
  font-weight: 300;
  color: #fff;
  opacity: 0.8;
  text-decoration: none;
}
.bottom-details .bottom_text a:hover{
  opacity: 1;
  text-decoration: underline;
}
.bottom-details .bottom_text a{
  margin-right: 10px;
}
    media (max-width: 900px) {
  footer .content .link-boxes{
    flex-wrap: wrap;
  }
  footer .content .link-boxes .input-box{
    width: 40%;
    margin-top: 10px;
  }
}
    media (max-width: 700px){
  footer{
    position: relative;
  }
  .content .top .logo-details{
    font-size: 26px;
  }
  .content .top .media-icons a{
    height: 35px;
    width: 35px;
    font-size: 14px;
    line-height: 35px;
  }
  footer .content .link-boxes .box{
    width: calc(100% / 3 - 10px);
  }
  footer .content .link-boxes .input-box{
    width: 60%;
  }
  .bottom-details .bottom_text span,
  .bottom-details .bottom_text a{
    font-size: 12px;
  }
}
    media (max-width: 520px){
  footer::before{
    top: 145px;
  }
  footer .content .top{
    flex-direction: column;
  }
  .content .top .media-icons{
    margin-top: 16px;
  }
  footer .content .link-boxes .box{
    width: calc(100% / 2 - 10px);
  }
  footer .content .link-boxes .input-box{
    width: 100%;
  }
}





</style>